### ISSUE TITLE
CI clean-up & newer compiler support for 2023

### ISSUE THREAD

**Issue by Kleidukos** [ExtremaIS/literatex-haskell#2]
Hi @TravisCardwell!
I'm migrating some of my libraries that depend on a literatex-based documentation generation, and I wanted to know if you were open to contributions in the following areas of your CI:

* Up-to-date support for newest minor versions of already-support compilers
* New support for newer compilers (9.4 and 9.6)
* clean-up of obsolete versions (minimum version: 8.10.7 that was released in mid-2021)

What do you think? I also have a tool that generates your CI jobs from your cabal files, you might be interested. It really helps with keeping metadata in sync.

**Comment by TravisCardwell** [comment]
Hi Hécate!

I am happy that LiterateX is useful for you!  Thank you for the issue!

I try to keep up with GHC releases, as well as occasionally update Stack releases.  I do this in the [`develop`][] branch, reserving the `main` branch for releases so that it is always stable.

[`develop`]: <https://github.com/ExtremaIS/literatex-haskell/tree/develop>

[Currently tested versions](https://github.com/ExtremaIS/literatex-haskell/blob/develop/literatex.cabal#L20-L28):

```
tested-with:
  GHC ==8.2.2
   || ==8.4.4
   || ==8.6.5
   || ==8.8.4
   || ==8.10.7
   || ==9.0.2
   || ==9.2.7
   || ==9.4.4
```

I have GHC 9.6.1 in my TODO matrix.  I did not add it this weekend because the Stack bindists and global hints had not been added yet.  They have since been added, so I will add support/tests for that version soon!

My personal goal is to support five years or more of GHC, Cabal, and dependencies (when possible).  I do not think that the official "three major versions" policy is sufficient for industry, as it only provides about 2~2.5 years of support for each version.

After the discussion about testing lower bounds with Joachim Breitner earlier this year, I am currently in the process of cleaning up the CI configuration of all my projects ([blog entry][]).  I have a few relevant goals:

[blog entry]: <https://www.extrema.is/blog/2023/01/14/github-actions-scripted-matrix>

* I would like to manage tested versions for both local testing (`Makefile`) and GitHub Actions in the same way.  I have configured TTC to use a [`test-all.sh`][] script that parses the `.cabal` file for running tests using Cabal and Stack, as well as generate the JSON for GitHub Actions.
* I would like to configure the CI for all of my projects consistently.  There are still a few things that I plan on experimenting with, and I plan on updating all of the projects (including this one) after those experiments are complete.

[`test-all.sh`]: <https://github.com/ExtremaIS/ttc-haskell/blob/develop/test-all.sh>

I have seen Joachim's [`cabal-plan-bounds`][] as well as your [`get-tested`][] utilities, and they both look really useful!  I do not use `get-tested` in my projects because I do not want to add a development environment dependency, as well as the first goal above.

[`cabal-plan-bounds`]: <https://github.com/nomeata/cabal-plan-bounds>
[`get-tested`]: <https://github.com/Kleidukos/get-tested>

BTW, I have not been creating Hackage revisions to update `tested-with` when adding tests for new GHC versions, but I have realized that I should.  I have a column for that in my TODO matrix!

**Comment by Kleidukos** [comment]
Perfect, then I can close this ticket. 

Don't hesitate to broadcast if you ever need some hands for some tasks. https://haskellweekly.news is always happy to relay such calls.

**Comment by TravisCardwell** [comment]
Hi @Kleidukos!

I just released [LiterateX 0.2.1.0][] with the following changes:

* An [`MdBook`][] output format is added.  It does not configure line numbering in any case, since per-block line numbering is not supported by mdBook.
* After over a year of Hackage revisions, the `main` branch is finally in sync!
* Dependency bounds are now explicitly tested, using [`cabal-bounds-lower.project`][] and [`cabal-bounds-upper.project`][].
* The project [links][] documentation now has a link to Flora!
* The project documentation now has a section on [branches][].

I also wrote a [Literate Haskell Markdown Headings][] blog post that describes the issue with using ATX-style headings in Literate Haskell source and includes an example workaround.

As I write this, docs are still pending on [Hackage][].  I will confirm that the build succeeds later today.

[LiterateX 0.2.1.0]: <https://github.com/ExtremaIS/literatex-haskell/releases/tag/literatex-haskell-0.2.1.0>
[`MdBook`]: <https://github.com/ExtremaIS/literatex-haskell/blob/13c721a4ef706e13cd0925370f9a06c59b05c614/src/LiterateX/Types/TargetFormat.hs#L49>
[`cabal-bounds-lower.project`]: <https://github.com/ExtremaIS/literatex-haskell/blob/main/cabal-bounds-lower.project>
[`cabal-bounds-upper.project`]: <https://github.com/ExtremaIS/literatex-haskell/blob/main/cabal-bounds-upper.project>
[links]: <https://github.com/ExtremaIS/literatex-haskell#links>
[branches]: <https://github.com/ExtremaIS/literatex-haskell#branches>
[Literate Haskell Markdown Headings]: <https://www.extrema.is/blog/2023/03/21/literate-haskell-markdown-headings>
[Hackage]: <https://hackage.haskell.org/package/literatex-0.2.1.0>

**Comment by tchoutri** [comment]
Hurray!! :tada:

**Comment by Kleidukos** [comment]
Hurray! :tada:
